apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application3
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/srinivasoggi/sonarqube.git
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
